POST 'http://localhost:8080/users'
Content-Type: application/json

{
    "userDNI": "38412522",
    "userFullName": "Nuevo Usuario",
    "userEmail": "unusuario@gmail.com",
    "userPhoneNumber": "341420542",
    "userTotalReserves": 4
}

###RECUPERAR TODOS LOS USUARIOS
GET 'http://localhost:8081/users'