###RECUPERAR TODOS LOS EMPLEADOS
GET http://localhost:8081/employees
###CREAR EMPLEADO
POST http://localhost:8081/employees
Content-Type: application/json

{
    "cuil": "39-41312139-4",
    "nameAndSurname": "Patricio Gonzalez"
}