###RECUPERA TODAS LAS CANCHAS
GET http://localhost:8081/fields
###CREAR UNA CANCHA
POST http://localhost:8081/fields
Content-Type: application/json

{
    "fieldType": 7,
    "fieldStatus": true,
    "fieldDimensions": "15x25" 
}