###RECUPERAR TODOS LOS EMPLEADOS
GET http://localhost:8081/employees

###RECUPERAR UN EMPLEADO
GET http://localhost:8081/employees/w6xjzw3KHOmVXK2ouoR3uXqO
###CREAR EMPLEADO
POST http://localhost:8081/employees
Content-Type: application/json

{
    "cuil": "20-39147457-4",
    "nameAndSurname": "Javier Milei"
}
###ACTUALIZAR EMPLEADO
PATCH http://localhost:8081/employees/e6048200-5b19-48fc-a329-b051287ff1fd
Content-Type: application/json

{
    "nameAndSurname": "Javier Milei"
}
###BORRAR EMPLEADO
DELETE http://localhost:8081/employees/e6048200-5b19-48fc-a329-b051287ff1fd