###RECUPERAR TODAS LAS PARRILLAS
GET http://localhost:8081/grills
###CREAR UNA PARRILLA
POST http://localhost:8081/grills
Content-Type: application/json

{
    "dimentions": "3.5x6",
    "grillStatus": true
}
###RECUPERAR UNA PARRILLA
GET http://localhost:8081/grill/
###MODIFICAR UNA PARRILLA   
PATCH http://localhost:8081/grill/
###BORRAR UNA PARRILLA
DELETE http://localhost:8081/grill/