###OBTENER TODOS LOS USUARIOS
GET http://localhost:8080/users
###CREAR UN USUARIO
POST http://localhost:8080/users
Content-Type: application/json

{
    
}
###OBTENER UN USUARIO
GET http://localhost:8080/user/
###MODIFICAR UN USUSARIO
PATCH http://localhost:8080/user/
###ELIMINAR UN USUARIO
DELETE http://localhost:8080/user/